### ISSUE TITLE
Criar tela de Login

### ISSUE THREAD

**Issue by rogeriorrodrigues** [rogeriorrodrigues/mbadevopsusp#1]
Preciso criar uma tela de login para conectar ao app com :
- Microsoft Entra ID
- Google Auth
- Apple ID account
- X ID Account

**Comment by rogeriorrodrigues** [comment]
O arquivo foi concluido com sucesso

**Comment by closerhan** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
bluemagma612, @kota5115, @noahspoke, @ShaydeNofziger, @MonkeyWhisperer, @onenonlycasper, @rollingStone91, @darkcrash, @jackbtsl, @vdharashive, @MahadevanAlagar1978, @atherdon, @sandrawangyx, @charmainekate, @laveenrose, @JanivZ, @mjjafari8, @conmute, @adriaesteve, @Lokesh-Chandra1, @jluisflo, @mmercuri, @ntheile, @solomonsayings, @vishal-shirodkar, @cyballnp1, @Nektarium, @jeffprestes, @clu3io, @AwesomeObserver, @loic35, @pauloesantos, @Sh1d0w, @yangyiming, @idowuakinde, @cfvote, @sandeeptalabathula, @ujweng, @kleffew94, @mateusdemboski, @ackuser, @akmstr, @21Ahmad, @PdroCorrea, @weihangChen, @jeffryvu, @MChorfa, @boborder, @kamalkishorm, @keleffewArjunAranetaCodes, @mishalmsb, @pnigos, @arwinneil, @Nektarium, @everton-e26, @v-rawang, @Zaihsgdg4ceh, @brainsoftca, @QuasarChains, @powerdude, @paladique, @suensummit, @shirmanov, @wpank, @RubenMagallanes, @pranavq212, @escodel, @zulhfreelancer, @ConaGo, @403418, @rohit-sharma, @Sh1d0w, @ShaydeNofziger, @nitingpt000, @sayanghosh123, @assassin316, @marttp, @NeilC, @michelloworld, @jeffprestes, @Protamandua, @JackieChainnn, @mrtpain, @grassmu, @ServerDestroyer, @tzementzali, @tirtangumilar, @midudu, @PrahaladBhagat, @rogerlau, @CreoDAMO, @gtamasSCS, @jurby, @rollingStone91, @kota5115, @PdroCorrea, @sivachamarthi, @manolaz, @dermatologist
